keydb:
  image:
    repository: eqalpha/keydb
    tag: 6.0.16
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  config: |
    multi-master no
    active-replication yes
haproxy:
  image:
    repository: haproxy
    tag: 2.3.4
    pullPolicy: IfNotPresent
  replicaCount: 2
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  config: |
    global
      log /dev/log local0
      chroot /var/lib/haproxy
      stats socket /run/haproxy/admin.sock mode 660 level admin
      stats timeout 30s
      user haproxy
      group haproxy
      daemon
    defaults
      log global
      mode tcp
      option tcplog
      timeout connect 5000ms
      timeout client  50000ms
      timeout server  50000ms
    listen keydb
      bind *:6379
      mode tcp
      balance roundrobin
      option tcp-check
      tcp-check send PING\r\n
      tcp-check expect string +PONG
      tcp-check send info replication\r\n
      tcp-check expect string role: master
      tcp-check send QUIT\r\n
      tcp-check expect string +OK

replication:
  keydb:
    replicaof:
      0: [1, 2]
      1: [0, 2]
      2: [0, 1]
  haproxy:
    server:
      0: maxconn 20000 check inter 1s
      1: maxconn 20000 check inter 1s backup
      2: maxconn 20000 check inter 1s backup
